services:
  - type: web
    name: vitaclin
    runtime: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: gunicorn vitaclin.wsgi:application